graph TD;
    A["新媒体文件生成 (消息通知)"] --> B["file scan 收到消息 根据URI查数据库"]
    B --> C{"是否 JPG 文件?"}
    C -- "是" --> E{"JPG 是否 NSFW?"}
    E -- "是" --> F["删除 JPG (流程结束)"]
    E -- "否" --> D["检查xmp"]
    D -- "否" --> G["保留 JPG (流程结束)"]
    D -- "是" --> H["提取对应 MP4 文件送检"]
    H --> I{"MP4 是否 NSFW?"}
    I -- "是" --> J["删除 JPG 和临时 MP4 文件"]
    I -- "否" --> K["保留 JPG 并删除临时 MP4 文件"]